[PACKAGE]
name=atd_motion_detector
version=1.0.0
architecture=all
depends=axis-libs-base,opencv,boost
vendor=Independent Developer
size=4096

[SCRIPTS]
preinstall=
postinstall=scripts/setup.sh
preuninstall=
postuninstall=

[WWW_RESOURCES]
dir=www

[BINARIES]
dir=bin